### ISSUE TITLE
Documentation for readoutmodules for 2.10

### ISSUE THREAD

**Issue by jcfreeman2** [DUNE-DAQ/readoutmodules#1]
Similar to the documentation requests for [fdreadoutlibs](https://github.com/DUNE-DAQ/fdreadoutlibs/issues/1) and [ndreadoutlibs](https://github.com/DUNE-DAQ/ndreadoutlibs/issues/1), it would be good to create documentation for this package before the 2.10 release. Some sections of the readoutlibs documentation can be moved into this package's documentation, e.g., the section describing generation of configs (`python -m readout.app_confgen -n 2 app.json`, etc.). It would also be nice if each module got a brief description. In some cases the comment at the top of the DAQ module's header file could even be used. E.g.

_FakeCardReader: Generates user payloads at a given rate, from WIB to FELIX binary capture. This implementation is purely software based, no FELIX card and tools are needed to use this module. A current TODO is to make it generic, to consume other types of user payloads._

though for other modules perhaps additional info would be helpful.

**Comment by roland-sipos** [comment]
I'm pretty sure Florian fixed this back at the time. If further tuning of the docs are needed, I would prefer to open another Issue, pointing exactly to remaining problems.
