### ISSUE TITLE
Support readout standalone configuration script for tests with WIB/TP fake card reader 

### ISSUE THREAD

**Issue by hristovaivana** [DUNE-DAQ/readoutmodules#14]
We asked Eric to adapt the readout standalone configuration script to work with the new IO Manager since dunedaq-v3.0.0. 
The change is being tested using tp_frames.bin file and the felix fake card reader for the TP link.
The following branch will be merged:
https://github.com/DUNE-DAQ/readoutmodules/tree/eflumerf/UpdateAppConfgen

**Comment by hristovaivana** [comment]
Eric's branch should be merged to develop.
https://github.com/DUNE-DAQ/readoutmodules/tree/eflumerf/UpdateAppConfgen

@dingp , shall I request a PR for Eric's branch?

**Comment by hristovaivana** [comment]
I have the following problem when testing Eric's branch with the latest nightly N22-07-07. When building the local area with:
dbt-build -j 16 
I expect to find the following file generated and placed here:
sourcecode/readoutmodules/scripts/readoutapp_gen
however this fails at the moment in my setup/tests. 

Can someone advise on the best procedure to test Eric's branch and merge it to develop. After that we can continue updating it for the needs of the readout development.
But I think I misunderstood the flow of dbt commands, now I think that the "scripts" directory and the config generation script inside it were created while the branch was checked out or merged e.g.:

git clone https://github.com/DUNE-DAQ/readoutmodules.git -b develop
git checkout -b hristova/UpdateAppConfgen
git merge eflumerf/UpdateAppConfgen

as a result this file was created
sourcecode/readoutmodules/scripts/readoutapp_gen

**Comment by bieryAtFnal** [comment]
@hristovaivana , two notes from me:

1. I updated Eric's branch with the latest changes on the develop branch.  I'm hopeful that this doesn't affect any of your tests, but I wanted to let you know.  I did this in the spirit of keeping Eric's branch current with other changes in the readoutmodules repo and other parts of the system.
2. After doing that merge, I ran 'dbt-build -j16 --clean', and I saw a copy of readoutapp_gen appear in install/readoutmodules/bin.

Here are the exact steps I used for the build
```
source /cvmfs/dunedaq.opensciencegrid.org/setup_dunedaq.sh
setup_dbt latest-spack
dbt-create -c -n N22-07-07 test_area
cd test_area
cd sourcecode
git clone https://github.com/DUNE-DAQ/readoutmodules.git -b eflumerf/UpdateAppConfgen
cd ..
dbt-workarea-env
dbt-build -j16
find . -name readoutapp_gen -type f -print 
```

**Comment by hristovaivana** [comment]
@bieryAtFnal  this is great, thank you very much. I will reproduce your recipe and let you know if it behaves the same. A few more comments/questions will follow. Also many thanks for updating Eric's branch with the latest changes in develop, this is 
very good and I don't expect this to have impact on our tests, but I will check. Realted to that, there was a branch `eflumerf/UpdateDQMConfgen` in daqconf but it seemed to have been merged to develop a long time ago.

1. As reported originally, I noticed differences in the behaviour between these two nighlies, N22-06-23 and N22-07-07, and now I just want to confirm this by posting the output from Kurt's command above (thanks, that proved to be handy):

with N22-07-07:
```
find . -name readoutapp_gen -type f -print
./sourcecode/readoutmodules/scripts/readoutapp_gen
```
with N22-06-23:
```
find . -name readoutapp_gen -type f -print
./sourcecode/readoutmodules/scripts/readoutapp_gen
./install/readoutmodules/bin/readoutapp_gen
```
2. Now I start from a clean setup and repeat Kurt's recipe. It works!!! It's nice that the command is available in the path too, e.g.
`readoutapp_gen -h` works.

3. I confirm that Eric's branch works for our test but we would like to continue readout-specific development on the readout configuration script itself `sourcecode/readoutmodules/python/readoutmodules/app_confgen.py`, e.g. adding an option to set the channel map. How shall we proceed? Should we merge Eric's branch to develop at this point and after that commit changes in our won new branches, make PRs, etc following the instructions and keeping up with the development cycle for each release.

4. @eflumerf thanks for all these changes to keep things running post-dunedaq-v2.x.x.

**Comment by hristovaivana** [comment]
Testing TP standalone configuration script with dunedaq-v3.1.0:
```
1. Download tp_frames.bin file
curl https://cernbox.cern.ch/index.php/s/FqMXxSpM3WjgeCN/download -o tp_frames.bin

2. Setup v3.1.0 work area and checkout branch
git clone https://github.com/DUNE-DAQ/readoutmodules.git -b hristova/tp_appconfgen_fix
dbt-build -j16

3. Check TP standalone configuration script was installed
find . -name readoutapp_gen -type f -print
readoutapp_gen -h

4. Generate configuration (TP links only, WIB2 format)
readoutapp_gen -n 0 -t 1 -c 2048 -m VDColdboxChannelMap tpapp.json

5. Run test job with nanorc
rm -Rf RunConf_1; nanorc tpapp.json test boot conf start_run 001 wait 10 stop_run scrap terminate
```
The fix in branch https://github.com/DUNE-DAQ/readoutmodules/tree/hristova/tp_appconfgen_fix 
allows the WIB2 configuration options to be used , i.e. "-c 2048 -m VDColdboxChannelMap".

**Comment by hristovaivana** [comment]
This is fixed in the branch above and merged to develop today. Thanks!
